/* eslint-disable import/no-unresolved */
// @ts-nocheck
export const chainId = "31337";
export * as AssetRouterCraftBeacon from "./AssetRouterCraftBeacon.js";
export * as AssetRouterCraftImplementation from "./AssetRouterCraftImplementation.js";
export * as AssetRouterInputBeacon from "./AssetRouterInputBeacon.js";
export * as AssetRouterInputImplementation from "./AssetRouterInputImplementation.js";
export * as AssetRouterOutputBeacon from "./AssetRouterOutputBeacon.js";
export * as AssetRouterOutputImplementation from "./AssetRouterOutputImplementation.js";
export * as BlockNumberImplementation from "./BlockNumberImplementation.js";
export * as ERC1155MintableBeacon from "./ERC1155MintableBeacon.js";
export * as ERC1155MintableImplementation from "./ERC1155MintableImplementation.js";
export * as ERC1820RegistryImplementation from "./ERC1820RegistryImplementation.js";
export * as ERC20MintableBeacon from "./ERC20MintableBeacon.js";
export * as ERC20MintableImplementation from "./ERC20MintableImplementation.js";
export * as ERC2981Setter0 from "./ERC2981Setter-0.js";
export * as ERC2981SetterBeacon from "./ERC2981SetterBeacon.js";
export * as ERC2981SetterImplementation from "./ERC2981SetterImplementation.js";
export * as ERC721MintableAutoIdBeacon from "./ERC721MintableAutoIdBeacon.js";
export * as ERC721MintableAutoIdImplementation from "./ERC721MintableAutoIdImplementation.js";
export * as ERC721MintableBeacon from "./ERC721MintableBeacon.js";
export * as ERC721MintableImplementation from "./ERC721MintableImplementation.js";
export * as Multicall2Implementation from "./Multicall2Implementation.js";
export * as ProxyFactory from "./ProxyFactory.js";
export * as TokenDna0 from "./TokenDna-0.js";
export * as TokenDnaBeacon from "./TokenDnaBeacon.js";
export * as TokenDnaImplementation from "./TokenDnaImplementation.js";
export * as TokenURI0 from "./TokenURI-0.js";
export * as TokenURIBaseURI0 from "./TokenURIBaseURI-0.js";
export * as TokenURIBaseURIBeacon from "./TokenURIBaseURIBeacon.js";
export * as TokenURIBaseURIImplementation from "./TokenURIBaseURIImplementation.js";
export * as TokenURIBeacon from "./TokenURIBeacon.js";
export * as TokenURIDna0 from "./TokenURIDna-0.js";
export * as TokenURIDnaBeacon from "./TokenURIDnaBeacon.js";
export * as TokenURIDnaImplementation from "./TokenURIDnaImplementation.js";
export * as TokenURIImplementation from "./TokenURIImplementation.js";
